#!/bin/bash

function cleanup_apt( ) {
    apt-get clean
    rm -rf /var/lib/apt/lists/*
}

trap cleanup_apt EXIT

export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get install -qy --no-install-recommends $@
