language: node_js
dist: trusty
sudo: false
node_js:
  - "8"
branches:
  only:
  - master
before_install:
  - cd src
  - cp environments/travis.env current.env
  - . ./current.env
script:
  - npm test --silent
