language: node_js
dist: trusty
sudo: false
node_js:
  - "8"
addons:
  postgresql: "9.6"
services:
  - postgresql
cache:
  directories:
    - $HOME/node_modules
branches:
  except:
    - prod
    - stg
    - stable
before_install:
  - psql --version
  - cp env/travis.env current.env
  - . ./current.env
script:
  - npm test --silent
  - npm run db-migrate --silent
  - npm run test-full --silent
after_script:
  - npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
