version: "3"
services:
  integration:
    build:
      context: src
      dockerfile: Dockerfile.integration
    depends_on:
      - webapp
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_NAME: feedback
      DB_USER: feedback
      DB_USER_PASSWORD: ""
  webapp:
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      NODE_ENV: development
      LOG_SERVICE_ERRORS: 1
      FIX_TIME_FOR_TESTING: 1
      LOG_LEVEL: "DEBUG"
      DB_HOST: database
      DB_NAME: feedback
      DB_USER: feedback
      DB_USER_PASSWORD: ""
  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: feedback
      POSTGRES_DB: feedback
